
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class conversial extends javax.swing.JFrame {

    /**
     * Creates new form conversial
     */
    public conversial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtJudul = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtIdentitas = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtNis = new javax.swing.JLabel();
        txtNama = new javax.swing.JLabel();
        cmbKelas = new javax.swing.JLabel();
        txtNamaDudi = new javax.swing.JLabel();
        txtAlamatdudi = new javax.swing.JLabel();
        txtDurasi = new javax.swing.JLabel();
        txtNiss = new javax.swing.JTextField();
        txtNamaa = new javax.swing.JTextField();
        txtNamadudii = new javax.swing.JTextField();
        cmbKelass = new javax.swing.JComboBox<>();
        txtAlamatdudii = new javax.swing.JTextField();
        txtDurasii = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        txtBulan = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtNilai = new javax.swing.JLabel();
        txtNilaii = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        txtKepemimpinan = new javax.swing.JLabel();
        txtKedisiplinan = new javax.swing.JLabel();
        txtKerjatim = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtKejuruan = new javax.swing.JLabel();
        txtManajerial = new javax.swing.JLabel();
        txtRerata = new javax.swing.JLabel();
        txtPredikat = new javax.swing.JLabel();
        txtKeterangan = new javax.swing.JLabel();
        txtKepemimpinann = new javax.swing.JTextField();
        txtKedisiplinann = new javax.swing.JTextField();
        txtKerjatimm = new javax.swing.JTextField();
        txtKejuruann = new javax.swing.JTextField();
        txtManajeriall = new javax.swing.JTextField();
        txtRerataa = new javax.swing.JTextField();
        txtPredikatt = new javax.swing.JTextField();
        txtKeterangann = new javax.swing.JTextField();
        btnKonversi = new javax.swing.JButton();
        btnIsilagi = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        txtJudul.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtJudul.setText("Sistem input Nilai PLK SMK Negeri 8 Semarang");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(txtJudul)
                .addGap(60, 60, 60))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(txtJudul)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        txtIdentitas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtIdentitas.setText("Data Identitas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtIdentitas)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtIdentitas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 102, 255));

        txtNis.setText("NIS               :");

        txtNama.setText("Nama           :");

        cmbKelas.setText("Kelas             :");

        txtNamaDudi.setText("Nama DUDI  :");

        txtAlamatdudi.setText("Alamat DUDI: ");

        txtDurasi.setText("Durasi           :");

        txtNiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNissActionPerformed(evt);
            }
        });
        txtNiss.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNissKeyTyped(evt);
            }
        });

        txtNamaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaaActionPerformed(evt);
            }
        });

        cmbKelass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih", "xi pplg  1", "xi pplg 2", "xi pplg 3", " ", " " }));
        cmbKelass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKelassActionPerformed(evt);
            }
        });

        txtAlamatdudii.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatdudiiActionPerformed(evt);
            }
        });

        txtDurasii.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDurasiiActionPerformed(evt);
            }
        });
        txtDurasii.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDurasiiKeyTyped(evt);
            }
        });

        txtBulan.setText("bulan");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtBulan)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(txtBulan))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cmbKelas)
                        .addGap(18, 18, 18)
                        .addComponent(cmbKelass, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtDurasi)
                        .addGap(18, 18, 18)
                        .addComponent(txtDurasii, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtAlamatdudi)
                        .addGap(18, 18, 18)
                        .addComponent(txtAlamatdudii))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtNamaDudi)
                        .addGap(18, 18, 18)
                        .addComponent(txtNamadudii))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtNama)
                        .addGap(18, 18, 18)
                        .addComponent(txtNamaa))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtNis)
                        .addGap(18, 18, 18)
                        .addComponent(txtNiss, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNis)
                    .addComponent(txtNiss))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama)
                    .addComponent(txtNamaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbKelas)
                            .addComponent(cmbKelass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNamaDudi)
                            .addComponent(txtNamadudii, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlamatdudi)
                            .addComponent(txtAlamatdudii, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDurasi)
                            .addComponent(txtDurasii, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(51, 255, 102));

        txtNilai.setText("Nilai:");

        txtNilaii.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNilaiiKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtNilai)
                .addGap(59, 59, 59)
                .addComponent(txtNilaii, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNilai)
                    .addComponent(txtNilaii, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));

        txtKepemimpinan.setText("kepemimpinan:");

        txtKedisiplinan.setText("Kedisiplinan    :");

        txtKerjatim.setText("Kerja tim         :");

        txtKejuruan.setText("Kejuruan         :");

        txtManajerial.setText("Manajerial      :");

        txtRerata.setText("Rerata            :");

        txtPredikat.setText("Predikat         :");

        txtKeterangan.setText("Keterangan    :");

        txtKepemimpinann.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKepemimpinannActionPerformed(evt);
            }
        });

        txtKedisiplinann.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKedisiplinannActionPerformed(evt);
            }
        });
        txtKedisiplinann.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKedisiplinannKeyTyped(evt);
            }
        });

        txtManajeriall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManajeriallActionPerformed(evt);
            }
        });
        txtManajeriall.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtManajeriallKeyTyped(evt);
            }
        });

        txtRerataa.setEnabled(false);
        txtRerataa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRerataaActionPerformed(evt);
            }
        });

        txtPredikatt.setEnabled(false);
        txtPredikatt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPredikattActionPerformed(evt);
            }
        });

        txtKeterangann.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtKeterangan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtKeterangann))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtPredikat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPredikatt))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtRerata)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRerataa))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtKejuruan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtKejuruann))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtKerjatim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtKerjatimm))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtKedisiplinan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtKedisiplinann))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtKepemimpinan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtKepemimpinann, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtManajerial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtManajeriall)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKepemimpinan)
                    .addComponent(txtKepemimpinann, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKedisiplinan)
                    .addComponent(txtKedisiplinann, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKerjatim)
                    .addComponent(txtKerjatimm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKejuruan)
                    .addComponent(txtKejuruann, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtManajerial)
                    .addComponent(txtManajeriall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRerata, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRerataa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPredikat)
                    .addComponent(txtPredikatt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKeterangan)
                    .addComponent(txtKeterangann, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnKonversi.setBackground(new java.awt.Color(204, 255, 204));
        btnKonversi.setText("konversi");
        btnKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonversiActionPerformed(evt);
            }
        });

        btnIsilagi.setBackground(new java.awt.Color(204, 255, 204));
        btnIsilagi.setText("isi lagi");
        btnIsilagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIsilagiActionPerformed(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(204, 255, 204));
        btnKeluar.setText("keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1)
                        .addGap(0, 76, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIsilagi, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIsilagi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKeluar)
                        .addGap(14, 14, 14)))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIsilagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIsilagiActionPerformed
txtNamaa.setText(null);
txtNiss.setText(null);
cmbKelass.setSelectedItem("pilih");
txtNamadudii.setText(null);
txtAlamatdudii.setText(null);
txtDurasii.setText(null);
txtNilaii.setText(null);
txtKepemimpinann.setText(null);
txtKedisiplinann.setText(null);
txtKerjatimm.setText(null);
txtKejuruann.setText(null);
txtManajeriall.setText(null);
txtRerataa.setText(null);
txtPredikatt.setText(null);
txtKeterangann.setText(null);

    }//GEN-LAST:event_btnIsilagiActionPerformed

    private void cmbKelassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKelassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKelassActionPerformed

    private void txtKepemimpinannActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKepemimpinannActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKepemimpinannActionPerformed

    private void txtKedisiplinannActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKedisiplinannActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKedisiplinannActionPerformed

    private void txtManajeriallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManajeriallActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_txtManajeriallActionPerformed

    private void txtRerataaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRerataaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRerataaActionPerformed

    private void txtNissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNissActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNissActionPerformed

    private void txtNamaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaaActionPerformed

    private void txtAlamatdudiiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatdudiiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatdudiiActionPerformed

    private void txtDurasiiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDurasiiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDurasiiActionPerformed

    private void btnKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonversiActionPerformed
if(txtNamaa.getText().equals(null)||
  txtNiss.getText().equals(null)||
  cmbKelass.getSelectedItem().equals("pilih")||
  txtNamadudii.getText().equals(null)||
  txtAlamatdudii.getText().equals(null)||
  txtDurasii.getText().equals(null)||
  txtNilaii.getText().equals(null)||
  txtKepemimpinann.getText().equals(null)||
  txtKedisiplinann.getText().equals(null)||
  txtKerjatimm.getText().equals(null)||
  txtKejuruann.getText().equals(null)||
  txtManajeriall.getText().equals(null)||
  txtRerataa.getText().equals(null)||
  txtPredikatt.getText().equals(null)||
  txtKeterangann.getText().equals(null)){
  JOptionPane.showMessageDialog(null,"tidakbolehkosong" );
}else{
 int nilai1=Integer.parseInt(txtKepemimpinann.getText());
 int nilai2=Integer.parseInt(txtKedisiplinann.getText());
 int nilai3=Integer.parseInt(txtKerjatimm.getText());
 int nilai4=Integer.parseInt(txtKejuruann.getText());
int nilai5=Integer.parseInt(txtManajeriall.getText());
double hasil=(nilai1+nilai2+nilai3+nilai4+nilai5)/5;
txtRerataa.setText(String.format("%.2f",hasil));
if (hasil > 100) {
    txtPredikatt.setText("Isikan 0-100");
    txtKeterangann.setText("Tidak Diketahui");
} else if (hasil>=91&&hasil<=100) {
        txtPredikatt.setText("Sangat Baik");
        txtKeterangann.setText("Sangat Kompeten");
    }
else if (hasil>=81&&hasil<=90) {
        txtPredikatt.setText("Baik");
        txtKeterangann.setText(" Kompeten");}
else if (hasil>=71&&hasil<=80) {
        txtPredikatt.setText("cukup");
        txtKeterangann.setText(" kurang Kompeten");}
else if (hasil>=61&&hasil<=70) {
        txtPredikatt.setText("kurang");
        txtKeterangann.setText("tidak Kompeten");}
else if (hasil>=0&&hasil<=61) {
        txtPredikatt.setText("sangat kurang");
        txtKeterangann.setText("tidak Kompeten");}
}
        

    }//GEN-LAST:event_btnKonversiActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
setExtendedState(berandaaa.MAXIMIZED_BOTH);  }

public void harusAngka(java.awt.event.KeyEvent evt){  
char karakter =evt.getKeyChar();
if(!Character.isDigit(karakter)){
evt.consume();//
}
    }//GEN-LAST:event_formWindowOpened

    private void txtNissKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNissKeyTyped
harusAngka(evt);       // TODO add your handling code here:
    }//GEN-LAST:event_txtNissKeyTyped

    private void txtDurasiiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDurasiiKeyTyped
harusAngka(evt) ;       // TODO add your handling code here:
    }//GEN-LAST:event_txtDurasiiKeyTyped

    private void txtNilaiiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNilaiiKeyTyped
harusAngka(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtNilaiiKeyTyped

    private void txtKedisiplinannKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKedisiplinannKeyTyped
harusAngka(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtKedisiplinannKeyTyped

    private void txtManajeriallKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtManajeriallKeyTyped
        // TODO add your handling code here:
        harusAngka(evt);  
    }//GEN-LAST:event_txtManajeriallKeyTyped

    private void txtPredikattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPredikattActionPerformed

    }//GEN-LAST:event_txtPredikattActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(conversial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(conversial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(conversial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(conversial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new conversial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIsilagi;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnKonversi;
    private javax.swing.JLabel cmbKelas;
    private javax.swing.JComboBox<String> cmbKelass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel txtAlamatdudi;
    private javax.swing.JTextField txtAlamatdudii;
    private javax.swing.JLabel txtBulan;
    private javax.swing.JLabel txtDurasi;
    private javax.swing.JTextField txtDurasii;
    private javax.swing.JLabel txtIdentitas;
    private javax.swing.JLabel txtJudul;
    private javax.swing.JLabel txtKedisiplinan;
    private javax.swing.JTextField txtKedisiplinann;
    private javax.swing.JLabel txtKejuruan;
    private javax.swing.JTextField txtKejuruann;
    private javax.swing.JLabel txtKepemimpinan;
    private javax.swing.JTextField txtKepemimpinann;
    private javax.swing.JLabel txtKerjatim;
    private javax.swing.JTextField txtKerjatimm;
    private javax.swing.JLabel txtKeterangan;
    private javax.swing.JTextField txtKeterangann;
    private javax.swing.JLabel txtManajerial;
    private javax.swing.JTextField txtManajeriall;
    private javax.swing.JLabel txtNama;
    private javax.swing.JLabel txtNamaDudi;
    private javax.swing.JTextField txtNamaa;
    private javax.swing.JTextField txtNamadudii;
    private javax.swing.JLabel txtNilai;
    private javax.swing.JTextField txtNilaii;
    private javax.swing.JLabel txtNis;
    private javax.swing.JTextField txtNiss;
    private javax.swing.JLabel txtPredikat;
    private javax.swing.JTextField txtPredikatt;
    private javax.swing.JLabel txtRerata;
    private javax.swing.JTextField txtRerataa;
    // End of variables declaration//GEN-END:variables
}
